# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ed04727df40ef19871b40f3515eca532016e8c2ad704ed517c7024cdba97d5a21cdfc343d27d258a1ecbcab5708bcaee3a2ac5e6e494110e7383f7bcec3ae8

test:
  secret_key_base: cf1fb72e1c2c4672e13e9891f9b59f9623ffaa5bb457c11e205acf831da5ab7911005dd0c73dabf4e96432dcac5deb951b81a8b9f12982d3125c6b77368b7e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
